version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8

    working_directory: ~/fragment

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-

      - run:
          name: Install
          command: yarn install --prefer-offline --pure-lockfile

      - run:
          name: Audit Dependency
          command: yarn audit

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      # run linter
      - run:
          name: Lint
          command: yarn lint

      # run tests
      - run:
          name: Test
          command: yarn test
